career_work = {
'money':['afford','ATM','auction','bailout','balance','bank','bankrupt','bankruptcy','bargain','bill','bonds','borrow','bought','budget','business','buy',
'capital','cash','cent','change','cheap','check','collateral','commodity','compound','coupon','credit','credit card','currency','debt','deficit','deposit','depression',
'dime','discount','diversify','dividend','dollar','donate','donation','donor','down payment','earn','earnings','economics','economist','economy','equity','estate','Euro','exchange',
'expense','expensive','finance','financier','fund','income','interest','invest','investment','investor','lend','lender','loan','loss','margin','market','mortgage','money','nickel','note',
'outgo','overdrawn','pay','payment','pence','penny','percentage','poor','portfolio','Pound','profit','purse','quarter','rate','rebate','receipt','recession','rent','reserve','rich','risk',
'sale','save','savings','security','sell','seller','sold','spend','stocks','surplus','swap','tax','teller','thrifty','trade','treasury','value','vault','wallet','wealth','withdraw','yield'],

'workplace':['accountant','accounting','accounts','accruals','ads','advertise','affordable','agenda','agreement','arbitration','benefits','bill of lading','board','board of directors',
'bond','bonus','bookkeeping','boss','bottom line','break even','briefcase','business card','buyer','calculate','capitalist','career','cargo','chairman','chairwoman','charge',
'clause','client','close','cold call','collateral','commerce','commercial','commission','commodity','company','competition','compromise','consumer','contract','copyright','corner office',
'corporate','corporation','cost','cubicle','currency','customer','database','deadline','deal','debit','deflation','demand','department','director','dismiss','distribution','diversify',
'dividend','down payment','download','duties','duty','economical','economics','economy of scale','efficiency','employ','employee','employer','employment','entrepreneur','equipment','estimate',
'executive','expenses','export','facility','factory','fax','figures','finance','financial','fire','foreman','framework','freight','fund','goods','graph','gross','growth','guidebook',
'head','hunter','headquarters','high','hire','hours','import','incentive','income','income tax','inflation','insurance','interest rate','intern','interview','inventory','invest','investment',
'invoice','job','labor','laborer','laptop','lead','lease','leave','letterhead','liability','loan','log-in','loss','low','lucrative','mailbox',
'mainframe','manage','management','manager','market','marketing','meeting','memo','merchandise','merchant','money','monopoly','motherboard',
'mouse pad','negotiate','negotiation','net','net worth','network','niche','no-win','notebook','notice','occupation','offer','office','offline',
'online','open','opportunity','order','organization','outgoing','overdraft','overhead','owner','packing list','paperweight','partner','password',
'perk','personnel','plan','policy','portfolio','position','presentation','president','price','prime rate','principal','product','production','profit',
'profitable','promotion','proposal','prospects','proxy','purchase order','purchasing','quit','rank','recruit','recruiter','refund','resign','retail',
'retailer','retire','résumé','risk','salary','salesman','saleswoman','secretary','service','shareholder','ship','shipment','shipping','shop ',
'sick leave','sign','signature','spreadsheet','staff','statement','stock','stockholder','strike','success','superintendent','supervisor','supply',
'target','tariff','temp','terms','trade-off','trainee','transaction','treasurer','treasury','trend','typeface','typewriter','unemployment','union',
'unit cost','upgrade','upload','username','vacancy','vacation time','venture','vice-president','video conference','volume','warranty','wastebasket',
'waybill','wholesale','wholesaler','win-win','withdraw','work','worker','workroom','workspace'],

'professions':['Accountant','Actor','Actress','Architect','Astronomer','Author','Baker','Bricklayer','Bus driver','Butcher','Carpenter','Chef','Cook','Cleaner',
'Dentist','Designer','Doctor','Dustman','Refuse collector','Electrician','Engineer','Factory worker','Farmer','Fireman','Fire fighter','Fisherman',
'Florist','Gardener','Hairdresser','Journalist','Judge','Lawyer','Lecturer','Librarian','Lifeguard','Mechanic','Model','Newsreader','Nurse','Optician',
'Painter','Pharmacist','Photographer','Pilot','Plumber','Politician','Policeman','Policewoman','Postman','Real estate agent','Receptionist','Scientist',
'Secretary','Shop assistant','Soldier','Tailor','Taxi driver','Teacher','Translator','Traffic warden','Travel agent','Veterinary doctor','Vet','Waiter',
'Waitress','Window cleaner'],

'teamwork':['collaboration','cooperation','harmony','synergy','coordination','partnership','coaction','team','unity','working together','team work',
'crew','collusion','collective work','solidarity','fellowship','esprit de corps','interplay','reciprocity','alliance','squad','association','concurrence',
'staff','joint action','interaction','joint effort','union','synergism','team effort','cohesion','joint operation','task force','team building','team-work','team-building',
'team spirit','collective action','team play','group','collaborative work'],

'growth':['increase','development','increases','expand','growing','recovery','regrowth','maturation','expand','thrive','flourish','gain','progress',
'develop','successful','high-flying','looked back','distinguished','brilliant','leading','incubation','enhancement','evolvement'],

'failure':['default','delinquency',' dereliction','misprision','neglect','negligence','nonfeasance','oversight','loser','incompetent','underachiever','disappointment','abortion',
'defeat','frustration','non-performance','omission','deficiency','malfunction','ruin','failing','foundering']
}

social_life = {
'family':['adoption','adoptive father','adoptive mother','ancestor','aunt','bachelor','birth mother','blood relative','bride','bridegroom','brother',
'brother-in-law','brotherhood','brotherly','care-giver','child','childhood','children','clan','close-knit','connection','cousin','dad','daddy','daughter','daughter-in-law',
'descendant','father','devoted','divorce','eligible','engaged','engagement','estranged','ex','ex husband','ex wife','extended family','faithful','family','family tree',
'father-in-law','fiancee','first born','first cousin','first cousin once removed','flesh and blood','folks','foster','foster child','foster father','foster mother',
'foster parent','fraternal','fraternal twin','friend','genealogy','grampa','gramps','grandchild','grandchildren','granddaughter','grandfather','grandma','grandmother',
'grandpa','grandparent','grandson','granny','great-aunt','great-granddaughter','great-grandfather','great-grandmother','great-grandparent','great-grandson','great-uncle',
'groom','grownup','half-brother','half-sister','heir','heiress','helpmate','hereditary','heritage','history','home','household','husband','identical twin','in-law',
'infancy','infant','inherit','inheritance','juvenile','kin','kindred','kinfolk','kinship','kith','lineage','love','loyalty','ma','maiden name','mama','marriage',
'mate','maternal','matriarch','matrimony','minor','Miss','mom','mommy','monogamy','mother','mother-in-law','Mr.','Mrs.','Ms.' ,'nana','natal','nephew','nest','newlywed',
'niece','nuclear family','nuptial','nurture','offspring','orphan' ,'papa','pa','parent','partner','paternal','patriarch','pop','posterity','progenitor','progeny',
'quadruplets','quads','quints','tupletquins','related','relations','relative','second cousin','senior','separation','sibling','single','sister','sister-in-law',
'sisterhood','sisterly','son','son-in-law','spouse','stepbrother','stepchild','stepchildren','stepdad','stepdaughter','stepfather','stepmom','stepmother','stepsister',
'stepson','support','surrogate mother','tribe','triplets','trust','trustworthy','twin brother','twin sister','twins','uncle','value','wed','wedding','wedlock','wife',
'youngster','youth'],

'friendship':['a friendly face','a helping hand','accord','acquaintance','admiration','adventure','advice','affection','ally','amigo','angel','back','best buds','best friend'
'blessing','blossoming friendship','bond','bosom buddy','brethren','brotherhood','buddy','camaraderie','caring','character',"chat",'cheer','chum','history','honesty',
'hug','humor','inspiration','interaction','joy','kindness','laughing','life','loyalty','mate','memories','mentor','old friend','pal','partner','patience','personality',
'playmate','presence','qualities','rapport','relationship','reliance','saint','sanity','closeness','club','comfort','communication','companion','companionship','company','concern',
'confidante','connection','conversation','decisions','devotion','discussion','disposition','encouragement','fellowship','forgiveness','free therapy','friend','friendly face',
'friendship','fun','girl friend','good times','happiness','security','sentiment','shared interests','shoulder','shoulder to cry on','sisterhood','smile','someone special','soul mate',
'spirit','strength','sunshine','support','supporter','team','therapist','therapy','thoughtfulness','thoughts','ties',"trust",'us','warmth','willingness','wisdom','worth'],

'couple_love':['Crush','Date','Boyfriend','Girlfriend','Fiancé','Fiancée','Partner','Husband','Wife','Better half','other half','Cute','Charming','Funny','Good looking','Pretty','Gorgeous','Handsome','Smart','Clever','Caring','Thoughtful','Considerate','Hug',
'Cuddle','Hold hands','To ask someone out','Go out','Get along','Treat','Invite','Flirt with','Flirt with','Break up','Split up','Fall out','Have a fight','To pop the question','To tie the knot','To be on the rocks','To make up','To play hard to get','Fall for','Fall in love',
'Be attracted to','Be compatible','Have a lot in common','Engaged','propose','Married','Single','divorced','Affair','Lover','Romance','Smitten','Sweetheart','Unrequited','Valentine','Stalker','Long Distance Relationship','Matchmaker'],

'art':['abstract','acrylic paint','airbrush','animation','architecture','art','art gallery','artist',"artist's bridge",'artistic','artwork','assemblage','bas-relief',
'batik','blending','bridge','brightness','brush','calligraphy','canvas','cartoon','carve','casting','cave drawing','ceramics','chalk','charcoal','chisel','clay',
'cloisonné','collage','color','color wheel','colored pencils','compass','composition','contrast','craft','crayon','create','creativity','critique','crosshatching',
'decorate','decorative','decoupage','depict','design','draw','drawing','easel','egg tempera','enamel','encaustic','engraving','erase','eraser','etching','exhibit',
'exhibition','film','form','frame','fresco','gallery','gesso','gilding','glass','glassblowing','glaze','gold leaf','gouache','graffiti','graphic design','graphite',
'hammer','hatching','high-relief','hue','illustrate','illustrat','ion','image','ink','installation','kiln','landscape','latex paint','line','liner brush','linseed oil',
'lithograph','lost wax method','low-relief','mahl stick','maquette','marble','marbling','marker','masterpiece','mechanical pencil','media','medium','mixed media',
'mobile','model','mosaic','mural','museum',"objets d'art",'oil paint','old master','op art','paint','paint roller','paintbrush','painter','painting','palette','palette knife',
'paper','pastel','pen','pencil','perspective','photo','photograph','pigment','porcelain','portfolio','portrait','portray','poster','pottery','pounce','primary color','print',
'printing','proportion','quill','quilt','quilting','realism','ruler','scale','screen printing','sculpt','sculptor','sculpture','seascape','secondary color','shade',
'silk screen','sketch','sketchbook','solvent','stained glass','stencil','still life','stippling','stone','stonecutting','style','t-square','tempera','template','textile arts',
'tole painting','tone','tools',"trompe l'oeil",'tube','turpentine','undertone','varnish','vellum','video','visual','watercolor','waterscape','wax','wheel','wood',
'wood carving','wood engraving','woodcut','woodcut print'],

'vacation':['airport','amusement park','airplane','bags','beach','baggage','boat','binoculars','camera','camping','cruise ship','campground','cruise','depart','destination','downtime','embark','excursion','explore','expedition','flight','foreign','garment bag','getaway','guide',
 'hostel', 'holiday','hotel','highway','island','itinerary' ,'jet','journey' ,'knapsack','luggage','landing','map','mountains','museum','national park','passport','photos','plane','passage','port','relax','reservations','restaurant','safari','ship','souvenir','stay','swim','subway','tour',
'tourist','train','travel','trip','vacation','visa','voyage','visit','weekend','waterpark','yacht','zoo']
}
health = {
'sport':['aerobics','archer','archery','arena','arrow','athlete','athletics','axel','ball','base','baseball','basketball','bat','baton','batter','batting',
'biathlon','bicycle','bicycling','bike','biking','billiards','bobsleigh','bocce','boomerang','boules','bow','bowler','bowling','boxer','boxing','bronze medal',
'bunt','canoe','canoeing','catch','catcher','champion','championship','cleats','club','coach','compete','competing','competition','competitor','crew','cricket',
'croquet','cross country','cue','curling','cycle','cycling','cyclist','dart','dartboard','deadlifting','decathlon','defense','diamond','discus','dive','diver',
'diving','dodgeball','doubleheader','dugout','épée','equestrian','equipment','exercise','fencing','field','field hockey','fielder','fielding','figure skating',
'fitness','football','forward','free throw','Frisbee','game','gear','geocaching','go','goal','goalie','gold medal','golf','golfer','golfing','guard','gym',
'gymnasium','gymnast','gymnastics','halftime','hammer throw','handball','hang gliding','hardball','helmet','heptathlon','high jump','hitter','hockey','hole-in-one',
'home plate','home run','home team','hoop','horses','hoes','huddle','hurdle','ice hockey','ice rink','ice skates','ice skating','infield','infielder','inline skates',
'inning','jai-alai','javelin','jog','jogger','judo','jump','jump rope','jumper','jumping','karate','kayak','kayaker','kayaking','kickball','kite','kneepads',
'kung fu','lacrosse','lawn bowling','league','long jump','lose','loser','luge','lutz','major league','mallet','martial arts','mat','medal','minor league',
'mitt','mouthguard','move','movement','MVP','net','no-hitter','Nordic skiing','offense','ollie','Olympics','orienteering','out','outfield','outfielder','paddle',
'paddleball','paddling','paintball','parasailing','parkour','pentathlon','pickleball','ping pong','pitch','pitcher','play','player','playing','playoffs','pogo stick',
'pole','pole vault','polo','pool','puck','quarter','quarterback','quiver','race','racer','racewalking','racing','racket','racquetball','rafting','referee','relay',
'ride','riding','rink','rock climbing','roller skates','roller skating','row','rower','rowing','rugby','run','runner','running','sailing','score','scoreboard',
'scuba','scull','sculling','shortstop','shot put','silver medal','skate','skating rink','skeleton','ski','skier','skiing','slalom','sled','sledder','sledding',
'snorkeling','snowboard','snowboarder','snowboarding','snowshoeing','soccer','softball','somersault','speed skating','sport','sportsmanship','squash','stadium',
'stick','strike','stroke','Sumo wrestling','surfer','surfing','swim','swimmer','swimming','synchronized swimming','table tennis','taekwondo','tag','target',
'team','teammate','tee','telemark skiing','tennis','tetherball','throw','throwing','tie','toboggan','track and field','trampoline','volley ball','walk','win','World Cup'
],

'nutrition':[' Aliment','Appearance',' Appetite','Balance','Behavior',' Benefit','Calcium','Calories','Carbohydrate','Circulation','Consumption','Cuisine','Diet','Digestion','Discipline','Energy','Fine foods','Fragrant',
'Gastronomy','Gourmet','Habit','Health','Homemade','Hungry','Hygiene','Lifestyle','Menu','Nutrition','Obesity','Organic','Overeat','Overweight','Potassium',' Preparation','Quantity','Regimen','Sanitary,','Snack','Starve','Transformation','Toxin' ,'Unhealthy,','Vegan','Vegetables','Viand',            
'Vitamin','Water','Weigh','Weight','Whole-grain','Yeast','Zinc'],

'depression':['Ability','Abnormal', 'Abuse', 'Adolescents', 'Affect', 'Agency', 'Aid', 'Alarm', 'Alienation', 'All ages', 'Alone', 'Anger', 'Anguish', 'Antidepressant', 'Anxiety', 'Anxious', 'Attempt', 'Attention', 'Attitude', 'Awareness',
'Bipolar', 'Blase', 'Blue', 'Brain','Caregiver', 'Certify', 'Child', 'Clarity', 'Clinical', 'Communication', 'Concern', 'Conclude', 'Condition', 'Confide', 'Confusion', 'Cooperative', 'Cope', 'Counsel', 'Courage', 'Cruel', 'Cure', 'Cycle','Data', 'Death', 'Debilitating', 'Defeated', 'Degree', 'Depressed', 'Depression', 'Descent', 'Despair', 'Detriment', 'Diagnosis', 'Die', 'Discrimination', 'Disease', 'Disinterest', 'Disorder', 'Disorder', 'Distracted', 'Doctor', 'Dog days', 'Down','Drugs'
,'Education', 'Effect', 'Endure', 'Esteem', 'Evaluation','Family', 'Fatigued', 'Fear', 'Feelings', 'Fight', 'Finality', 'Friends','Gain', 'Grief', 'Grieving', 'Guideline',
'Hard work', 'Heal', 'Health', 'Help', 'Helpless', 'Hereditary', 'Hopelessness', 'Hot-line', 'Hurt','Immune', 'Improvement', 'Inability', 'Inactivity', 'Indicator', 'Insecure', 'Interested', 'Interfere', 'Involvement', 'Irritable', 'Isolation', 'Issues','Jeer', 'Joking',
'Kill','Lack', 'Level','Listening','Medication', 'Medicine', 'Melancholia', 'Mental', 'Mental health', 'Misunderstanding', 'Monitor','Necessary', 'Need', 'Negative', 'Normal', 'Nothing', 'Overwhelmed',
'Pain', 'Panic', 'Patient', 'Pattern', 'Pay attention', 'Peers', 'Personal', 'Physician', 'Pills', 'Prescription', 'Prevent', 'Prevention', 'Programs', 'Progress', 'Protect', 'Psychiatrist','Report', 'Requirement', 
'Sadness', 'Scared', 'Security', 'Separation', 'Seriousness', 'Siblings', 'Signs', 'Skills', 'Sleep', 'Sleep pattern', 'Solitary', 'Sorrow', 'Source', 'Statistics', 'Stigma', 'Strength', 'Struggle', 'Studies', 'Substance abuse', 'Succor', 'Suffer', 'Suicide', 'Sympathetic', 'Symptoms'
,' Talk',  'Teenagers', 'Tentative', 'Terrified', 'Therapy', 'Thoughts',' Time', 'Tired', 'Tragedy', 'Tragic', 'Treat', 'Treatment', 'Triumph', 'Troubled'
,'Uncertain', 'Uncomfortable', 'Understanding', 'Unfulfilled', 'Unique', 'Unsettling','Validation', 'Victim','Warning', 'World Health Organization', 'Worry', 'Worthless'],

'addiction':['Abstinence','Acetaminophens','ACOA','Addict','Addiction Assessment','Addiction Treatment','Addiction','Addictive Personality','Adverse Reaction',
'Affinity' ,'Age at Onset'  ,'Agonist' ,'Alcoholics Anonymous' ,'Alkaloids','Amphetamine','Analgesic','Antagonist','AOD','AODA' ,'Aspirin' ,'Benzodiazepine',
'Bioavailability','Blood Alcohol Level','Caffeine','Carcinogen','Causal Factors','Ceiling Effect','Codependence','Codeine','Cold Turkey','Compulsion',
'Conditioning','Craving','Crisis Intervention','Cross-Dependence' ,'Cross-Tolerance','Denial','Detoxification','Detox','Disease','Dopamine' ,'Downers',
'Drug Misuse','Drug Tolerance','Dysphoria','Dysynergy','Enabling','Endogenous Opioid','Endorphins','Ethanol','Euphoria','Evidence-based Treatment',
'Excipient','Fetal Alcohol Syndrome','Fetal Drug Syndrome','Food and Drug Administration','Habit','Hallucinogen','Harm Reduction','Heroin','Hydrocodone',
'Induction','Inflation','Intoxication','Intrinsic Activity','Legal Drugs','Maintenance','Medical Model','Metabolism','Methadone','Monotherapy','Morphine',
'Mu Agonist','Mu Opioid Receptor','Naloxone','Naltrexone','Narcotic','National Board of Addiction Examiners (NBAE)''Negative Reinforcement',
'Neurotransmitter','Nicotine','Nonopioid','Obsession','Off-Label Use','Opiate','Opioids','Opium','Over-the-Counter Drugs','Oxycodone','Painkillers',
'Partial Agonists','Pharmacology','Physical Dependence','Placebo','Polysubstance Abuse','Post-Acute Withdrawal Syndrome (PAWS)','Precipitated Withdrawal Syndrome',
'Prescription Drugs','Psychedelic Drugs','Psychoactive Drug','Psychological Dependence','Psychopharmacology','Psychotropic Drug','Rapid Detox',
'Receptor','Recovery','Relapse','Remission','Reversed Tolerance','Screening','Self-Help Group','Side Effects','Societal Denial','Steroids','Stimulant',
'Straight-Edge','Sublingual','Substance Abuse','Substance Dependence','Synergism','Synthetic','Talc','Therapeutic Community','Therapeutic Dependence',
'Titration','Tolerance','Toxicity','Tranquilizers','Trigger','Uppers','Urge-Peak Cycle','Urge-Peak','Urges','User','Withdrawal Symptoms','Withdrawal Syndrome']
}
